Repository palazzem/ha-econnect-alarm, pull requests merged in 2023-09, with the labels that each got.

#10 package: update structure to support testing and building
  README.md
  custom_components/__init__.py
  custom_components/econnect_alarm/__init__.py
  custom_components/econnect_alarm/alarm_control_panel.py
  custom_components/econnect_alarm/binary_sensor.py
  custom_components/econnect_alarm/config_flow.py
  custom_components/econnect_alarm/const.py
  custom_components/econnect_alarm/decorators.py
  custom_components/econnect_alarm/exceptions.py
  custom_components/econnect_alarm/helpers.py
  custom_components/econnect_alarm/manifest.json
  custom_components/econnect_alarm/services.yaml
  custom_components/econnect_alarm/strings.json
  custom_components/econnect_alarm/translations/en.json
  pyproject.toml
  requirements_all.txt
  requirements_test_all.txt
  tests/components/econnect_alarm/__init__.py
  tests/conftest.py
  tests/hass/__init__.py
  tests/hass/common.py
  tests/hass/fixtures.py
  tests/hass/ignore_uncaught_exceptions.py
  tests/hass/syrupy.py
  tests/hass/test_util/__init__.py
  tests/hass/test_util/aiohttp.py
  tests/hass/typing.py
  tests/test_config_flow.py
Labels: topic:packaging, topic:tests, type:feature, type:refactor

#11 tools: use pre-commit hooks to run linters and static analyzers
  .pre-commit-config.yaml
  custom_components/econnect_alarm/__init__.py
  custom_components/econnect_alarm/alarm_control_panel.py
  custom_components/econnect_alarm/binary_sensor.py
  custom_components/econnect_alarm/config_flow.py
  custom_components/econnect_alarm/helpers.py
  custom_components/econnect_alarm/strings.json
  custom_components/econnect_alarm/translations/en.json
  tests/conftest.py
  tests/test_config_flow.py
Labels: topic:tools, type:feature

#12 tools: add `tox` to handle the project test matrix
  pyproject.toml
  tests/__init__.py
  tox.ini
Labels: topic:tools, type:feature

#13 tools: add GitHub templates for bug reporting / features / pull requests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: topic:tools, type:feature

#14 feat: add contribution guidelines
  CONTRIBUTING.md
Labels: type:docs, type:feature

#15 tools: add GitHub actions to provide CI for linting, testing and code coverage
  .github/workflows/linting.yaml
  .github/workflows/testing.yaml
  README.md
Labels: topic:tools, type:feature

#16 tools: add `hassfest` GitHub actions to validate the integration
  .github/workflows/hassfest.yaml
  .pre-commit-config.yaml
  custom_components/econnect_alarm/manifest.json
Labels: topic:tools, type:feature

#20 tools: add GitHub actions to automatically build the package on tag version
  .github/workflows/building.yaml
  pyproject.toml
Labels: topic:tools, type:feature

#21 fix(ci): builder action names the package with the right version using `hatch version`
  .github/workflows/building.yaml
  .github/workflows/linting.yaml
  .github/workflows/testing.yaml
Labels: topic:tools, type:bug

#28 feat: add `AlarmDevice` component
  custom_components/econnect_alarm/__init__.py
  custom_components/econnect_alarm/devices.py
  custom_components/econnect_alarm/manifest.json
  pyproject.toml
  tests/conftest.py
  tests/fixtures/__init__.py
  tests/fixtures/responses.py
  tests/hass/common.py
  tests/test_devices.py
Labels: topic:entity, type:feature

#34 feat: add support for `VACATION` mode
  custom_components/econnect_alarm/alarm_control_panel.py
  custom_components/econnect_alarm/config_flow.py
  custom_components/econnect_alarm/const.py
  custom_components/econnect_alarm/devices.py
  custom_components/econnect_alarm/strings.json
  custom_components/econnect_alarm/translations/en.json
  tests/test_devices.py
Labels: topic:entity, type:feature

#35 fix(config): allow users to remove configuration for alarm modes
  custom_components/econnect_alarm/helpers.py
  tests/test_helpers.py
Labels: topic:entity, type:bug

#31 feat: HACS installation support
  .github/workflows/publish.yaml
  README.md
  hacs.json
Labels: topic:packaging, type:feature

#39 fix(build): build runner ships a `zip` package instead of a `tar.gz`
  .github/workflows/building.yaml
  pyproject.toml
Labels: topic:tools, type:feature

#42 feat: add IT translation
  custom_components/econnect_alarm/translations/it.json
Labels: topic:packaging, type:feature

#43 docs: update documentation and UI to explain what to put in `domain`
  README.md
  custom_components/econnect_alarm/translations/en.json
  custom_components/econnect_alarm/translations/it.json
Labels: type:docs, type:feature

#44 refactor!: migrate the integration to `elmo_iess_alarm` namespace
  .github/workflows/building.yaml
  .github/workflows/publish.yaml
  .pre-commit-config.yaml
  README.md
  custom_components/elmo_iess_alarm/__init__.py
  custom_components/elmo_iess_alarm/alarm_control_panel.py
  custom_components/elmo_iess_alarm/binary_sensor.py
  custom_components/elmo_iess_alarm/config_flow.py
  custom_components/elmo_iess_alarm/const.py
  custom_components/elmo_iess_alarm/decorators.py
  custom_components/elmo_iess_alarm/devices.py
  custom_components/elmo_iess_alarm/exceptions.py
  custom_components/elmo_iess_alarm/helpers.py
  custom_components/elmo_iess_alarm/manifest.json
  custom_components/elmo_iess_alarm/services.yaml
  custom_components/elmo_iess_alarm/strings.json
  custom_components/elmo_iess_alarm/translations/en.json
  custom_components/elmo_iess_alarm/translations/it.json
  hacs.json
  pyproject.toml
  tests/conftest.py
  tests/test_config_flow.py
  tests/test_decorators.py
  tests/test_devices.py
  tests/test_helpers.py
Labels: breaking change, topic:entity, topic:packaging, type:refactor

#46 docs: update Elmo/IESS references with the latest screenshots
  README.md
  custom_components/elmo_iess_alarm/config_flow.py
  custom_components/elmo_iess_alarm/strings.json
  custom_components/elmo_iess_alarm/translations/en.json
  custom_components/elmo_iess_alarm/translations/it.json
  tests/test_config_flow.py
Labels: type:docs

#48 release: 1.0.0
  custom_components/elmo_iess_alarm/manifest.json
Labels: topic:release

#49 feat: add an alias to the control panel and binary sensor entities
  custom_components/elmo_iess_alarm/alarm_control_panel.py
  custom_components/elmo_iess_alarm/binary_sensor.py
  custom_components/elmo_iess_alarm/config_flow.py
  custom_components/elmo_iess_alarm/const.py
  custom_components/elmo_iess_alarm/helpers.py
  custom_components/elmo_iess_alarm/manifest.json
  custom_components/elmo_iess_alarm/strings.json
  custom_components/elmo_iess_alarm/translations/en.json
  custom_components/elmo_iess_alarm/translations/it.json
  tests/conftest.py
  tests/test_helpers.py
Labels: breaking change, topic:entity, type:feature

#52 refactor: use slugify function to generate the entity name as HA expects
  custom_components/elmo_iess_alarm/helpers.py
  pyproject.toml
  tests/test_helpers.py
Labels: topic:entity, type:refactor

#54 feat!: binary sensors and control panels generates a valid Entity ID with a human readable name
  custom_components/elmo_iess_alarm/alarm_control_panel.py
  custom_components/elmo_iess_alarm/binary_sensor.py
  custom_components/elmo_iess_alarm/helpers.py
  tests/conftest.py
  tests/test_alarm_panel.py
  tests/test_binary_sensors.py
  tests/test_helpers.py
Labels: breaking change, topic:entity, type:feature
