Repository palazzem/ha-econnect-alarm, pull requests merged in 2023-10, with the labels that each got.

#56 Update README.md
  README.md
Labels: type:docs

#58 feat(collector): support configurable scan interval to reduce data usage
  custom_components/elmo_iess_alarm/__init__.py
  custom_components/elmo_iess_alarm/config_flow.py
  custom_components/elmo_iess_alarm/const.py
  custom_components/elmo_iess_alarm/strings.json
  custom_components/elmo_iess_alarm/translations/en.json
  custom_components/elmo_iess_alarm/translations/it.json
Labels: topic:collector, type:feature

#57 feat: add system global states to monitor the central unit
  custom_components/elmo_iess_alarm/binary_sensor.py
  custom_components/elmo_iess_alarm/devices.py
  custom_components/elmo_iess_alarm/manifest.json
  custom_components/elmo_iess_alarm/strings.json
  custom_components/elmo_iess_alarm/translations/en.json
  custom_components/elmo_iess_alarm/translations/it.json
  pyproject.toml
  tests/conftest.py
  tests/fixtures/responses.py
  tests/test_binary_sensors.py
  tests/test_devices.py
Labels: topic:entity, type:feature

#62 docs: improve `homekit` section
  README.md
Labels: type:docs

#64 refactor!: rename the integration as `econnect_metronet`
  .github/workflows/building.yaml
  .github/workflows/publish.yaml
  .pre-commit-config.yaml
  README.md
  custom_components/econnect_metronet/__init__.py
  custom_components/econnect_metronet/alarm_control_panel.py
  custom_components/econnect_metronet/binary_sensor.py
  custom_components/econnect_metronet/config_flow.py
  custom_components/econnect_metronet/const.py
  custom_components/econnect_metronet/decorators.py
  custom_components/econnect_metronet/devices.py
  custom_components/econnect_metronet/exceptions.py
  custom_components/econnect_metronet/helpers.py
  custom_components/econnect_metronet/manifest.json
  custom_components/econnect_metronet/services.yaml
  custom_components/econnect_metronet/strings.json
  custom_components/econnect_metronet/translations/en.json
  custom_components/econnect_metronet/translations/it.json
  hacs.json
  pyproject.toml
  tests/conftest.py
  tests/test_alarm_panel.py
  tests/test_binary_sensors.py
  tests/test_config_flow.py
  tests/test_decorators.py
  tests/test_devices.py
  tests/test_helpers.py
Labels: breaking change, topic:packaging, type:refactor

#66 release: 2.0.0
  custom_components/econnect_metronet/manifest.json
Labels: topic:release

#67 ci(release): all packages are built during the release action
  .github/workflows/building.yaml
  .github/workflows/publish.yaml
Labels: topic:tools, type:refactor

#69 refactor: split binary sensors in their own entities
  custom_components/econnect_metronet/binary_sensor.py
  tests/conftest.py
  tests/test_binary_sensors.py
Labels: topic:entity, type:refactor

#71 refactor: add _inventory in AlarmDevice
  custom_components/econnect_metronet/devices.py
  tests/test_devices.py
Labels: topic:entity, type:refactor

#73 fix(collector): force an update when the integration fails an update
  custom_components/econnect_metronet/__init__.py
  custom_components/econnect_metronet/devices.py
  tests/test_devices.py
Labels: topic:collector, type:fix

#74 refactor: create `AlarmCoordinator` to separate HA functions from the fetching logic
  custom_components/econnect_metronet/__init__.py
  custom_components/econnect_metronet/coordinator.py
  custom_components/econnect_metronet/devices.py
  pyproject.toml
  tests/conftest.py
  tests/test_coordinator.py
  tests/test_devices.py
Labels: topic:collector, type:refactor

#78 fix: build system uploads only HACS files to prevent downloading errors
  .github/workflows/building.yaml
  .github/workflows/hassfest.yaml
  .github/workflows/linting.yaml
  .github/workflows/publish.yaml
  .github/workflows/testing.yaml
  pyproject.toml
Labels: topic:tools, topic:release, type:fix

#79 refactor: add `device.item` to query the inventory
  custom_components/econnect_metronet/binary_sensor.py
  custom_components/econnect_metronet/devices.py
  pyproject.toml
  tests/fixtures/responses.py
  tests/test_binary_sensors.py
  tests/test_coordinator.py
  tests/test_devices.py
Labels: topic:entity, type:refactor

#83 feat: auto-initialize tests alarm_device
  tests/conftest.py
  tests/test_binary_sensors.py
Labels: topic:tests, type:fix

#85 feat(experimental): add `force_update` as experimental setting in YAML conf
  .gitignore
  custom_components/econnect_metronet/__init__.py
  custom_components/econnect_metronet/binary_sensor.py
  tests/conftest.py
  tests/test_experiments.py
Labels: topic:entity, type:feature

#86 fix(experimental): namespace experimental settings under `experimental` key
  custom_components/econnect_metronet/binary_sensor.py
  custom_components/econnect_metronet/const.py
  tests/test_experimental_settings.py
Labels: topic:entity, type:fix

#88 feat: create InputSensors with _inventory
  custom_components/econnect_metronet/binary_sensor.py
  custom_components/econnect_metronet/devices.py
  tests/test_binary_sensors.py
  tests/test_devices.py
Labels: topic:entity, type:feature

#90 feat: add missing tests for binarysensors
  tests/conftest.py
  tests/fixtures/responses.py
  tests/test_binary_sensors.py
Labels: topic:tests

#91 ci: write xml code coverage for better coveralls support
  README.md
  pyproject.toml
  tox.ini
Labels: topic:tests, type:fix

#92 deps: update econnect-python to 0.8.0
  custom_components/econnect_metronet/manifest.json
  pyproject.toml
Labels: topic:packaging

#93 fix: restore previous unique id structure in `AlertSensor`
  custom_components/econnect_metronet/binary_sensor.py
  tests/test_binary_sensors.py
Labels: topic:entity, type:fix

#97 fix: read alerts last ids for polling
  custom_components/econnect_metronet/devices.py
  custom_components/econnect_metronet/manifest.json
  pyproject.toml
  tests/test_devices.py
Labels: topic:collector, type:fix

#98 release: 2.1.0
  custom_components/econnect_metronet/manifest.json
Labels: topic:release

#99 feat!: treat alarm_led, tamper_led and inputs_led as sensors
  custom_components/econnect_metronet/__init__.py
  custom_components/econnect_metronet/binary_sensor.py
  custom_components/econnect_metronet/sensor.py
  custom_components/econnect_metronet/translations/en.json
  custom_components/econnect_metronet/translations/it.json
  tests/test_binary_sensors.py
  tests/test_experimental_settings.py
  tests/test_sensors.py
Labels: topic:entity, type:feature
