Repository palazzem/ha-econnect-alarm, pull requests merged in 2023-12, with the labels that each got.

#111 feat: provide HA instance via `compose.yaml`
  .gitignore
  README.md
  compose.yaml
Labels: topic:tests, type:feature

#110 feat: add outputs status and command
  custom_components/econnect_metronet/__init__.py
  custom_components/econnect_metronet/const.py
  custom_components/econnect_metronet/devices.py
  custom_components/econnect_metronet/switch.py
  pyproject.toml
  tests/conftest.py
  tests/fixtures/responses.py
  tests/test_coordinator.py
  tests/test_devices.py
  tests/test_switch.py
Labels: topic:entity, type:feature

#113 deps: update `econnect-python` to version 0.9.0
  custom_components/econnect_metronet/manifest.json
  pyproject.toml
Labels: topic:packaging, type:feature

#114 release: v2.2.0
  custom_components/econnect_metronet/manifest.json
Labels: topic:release

#116 deps: update econnect-python to 0.9.1
  custom_components/econnect_metronet/manifest.json
  pyproject.toml
Labels: topic:collector, type:fix

#118 deps: add `async_timeout` package used in the `AlarmCoordinator`
  pyproject.toml
Labels: topic:packaging, type:fix
