Repository palazzem/ha-econnect-alarm, pull requests merged in 2024-02, with the labels that each got.

#125 feat: add `init` script to initialize a working devenv with a specific Home Assistant version
  .github/workflows/testing.yaml
  .gitignore
  README.md
  scripts/download_fixtures.sh
  scripts/init
  tests/hass/__init__.py
  tests/hass/common.py
  tests/hass/fixtures.py
  tests/hass/ignore_uncaught_exceptions.py
  tests/hass/syrupy.py
  tests/hass/test_util/__init__.py
  tests/hass/test_util/aiohttp.py
  tests/hass/typing.py
Labels: topic:tools, type:feature

#126 refactor: update `pre-commit` hooks
  .pre-commit-config.yaml
  custom_components/econnect_metronet/__init__.py
  custom_components/econnect_metronet/alarm_control_panel.py
  custom_components/econnect_metronet/binary_sensor.py
  custom_components/econnect_metronet/const.py
  custom_components/econnect_metronet/decorators.py
  custom_components/econnect_metronet/sensor.py
  tests/fixtures/responses.py
Labels: topic:tools, type:refactor

#127 fix: `econnect-python` logger can be enabled from UI
  README.md
  custom_components/econnect_metronet/manifest.json
Labels: topic:tools, type:fix

#128 fix(deprecation): replace constants deprecated in future versions of HA (2025.1)
  custom_components/econnect_metronet/alarm_control_panel.py
Labels: topic:entity, type:fix

#129 fix(config): `domain` field is required and pre-filled with `default`
  README.md
  custom_components/econnect_metronet/config_flow.py
  custom_components/econnect_metronet/strings.json
  custom_components/econnect_metronet/translations/en.json
  custom_components/econnect_metronet/translations/it.json
  tests/test_config_flow.py
Labels: topic:entity, type:fix

#130 fix(log): forcing a full update is not considered an error
  custom_components/econnect_metronet/coordinator.py
Labels: topic:collector, type:fix

#131 fix: set `CONFIG_SCHEMA` to accept configuration from config entries
  custom_components/econnect_metronet/__init__.py
Labels: topic:packaging, type:fix

#132 deps: update `econnect-python` to version 0.10.0
  custom_components/econnect_metronet/manifest.json
  pyproject.toml
Labels: topic:packaging, type:feature

#133 feat: catch `CommandError` exceptions
  custom_components/econnect_metronet/devices.py
Labels: topic:entity, topic:collector, type:feature

#135 feat: `AlarmDevice` queries panel details
  custom_components/econnect_metronet/devices.py
  custom_components/econnect_metronet/manifest.json
  pyproject.toml
  tests/fixtures/responses.py
  tests/test_coordinator.py
  tests/test_devices.py
Labels: topic:entity, type:feature

#137 fix(device): disarm only currently activated sectors to support users with limited permissions
  custom_components/econnect_metronet/devices.py
  tests/test_devices.py
Labels: topic:entity, type:fix

#138 fix(config): `experimental` settings are enabled again as internal config
  custom_components/econnect_metronet/__init__.py
Labels: topic:entity, type:fix

#142 docs: readme improvements for HomeKit integration
  .gitignore
  README.md
  images/alarm_panel_entity_id.png
  images/homekit_alarm_panel.jpg
  images/homekit_alarm_panel_open.png
Labels: type:fix, topic:docs

#144 feat: add arm/disarm sectors services to activate/deactivate a selection of sectors
  custom_components/econnect_metronet/__init__.py
  custom_components/econnect_metronet/binary_sensor.py
  custom_components/econnect_metronet/const.py
  custom_components/econnect_metronet/devices.py
  custom_components/econnect_metronet/services.py
  custom_components/econnect_metronet/services.yaml
  tests/test_binary_sensors.py
  tests/test_devices.py
  tests/test_services.py
Labels: topic:entity, type:feature

#145 fix: add missing icons for registered services
  custom_components/econnect_metronet/icons.json
Labels: topic:entity, type:fix

#146 feat(experimental): add managed sectors to control only part of available areas
  custom_components/econnect_metronet/__init__.py
  custom_components/econnect_metronet/const.py
  custom_components/econnect_metronet/devices.py
  tests/test_devices.py
Labels: topic:entity, type:feature

#147 release: v2.3.0
  custom_components/econnect_metronet/manifest.json
Labels: topic:release

#149 tests: disable DEBUG log level when `pytest` is launched with `--verbose`
  tests/conftest.py
Labels: topic:tests, type:fix
